### ISSUE TITLE
0027 line breaks and ##

### ISSUE THREAD

**Issue by espensj** [global-asp/gasp-alternates#1]
Hi!
There seems to be something off with 0027 in Arabic.

![ar-0027](https://cloud.githubusercontent.com/assets/12679303/23344287/9167c6a0-fc2e-11e6-9ccc-e9e6f1393357.png)

![ar-27-rendered](https://cloud.githubusercontent.com/assets/12679303/23344306/ff8d56d6-fc2e-11e6-9896-3373d9ce0fef.png)

I guess we just have to move the ## to the beginning?

E

**Comment by dohliam** [comment]
You're right, it's just missing a line break. Let's see whether this is still a problem after the new versions are uploaded.

**Comment by espensj** [comment]
The English version has a line break, but not a page break. Anyway, when we upload the revised version we'll check this.

**Comment by dohliam** [comment]
The last `##` in a story is not a page break per se, but indicates the beginning of the metadata section. All the stories have this, regardless of language. You can see it in the English version [here](https://raw.githubusercontent.com/global-asp/asp-source/master/en/0027_decision.md).
